name: PlatformIO CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Cache pip
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Cache PlatformIO
      uses: actions/cache@v2
      with:
        path: ~/.platformio
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
    - name: Set up Python
      uses: actions/setup-python@v2
    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade platformio
    - name: Build Banane_V1
      run: pio run -e Banane_V1
    - name: Build Banane_V1_noSD
      run: pio run -e Banane_V1_noSD
    # - name: Build Banane_V1_proto
    #   run: pio run -e Banane_V1_proto
    - name: Build matrix_64x64
      run: pio run -e matrix_64x64
    - name: Build matrix_cross
      run: pio run -e matrix_cross
    - name: Deploy
      env:
        SUPER_SECRET: ${{ secrets.TOKEN }} 
      run: |
        mv .pio/build/Banane_V1/firmware.bin         matrix_ble_player_Banane_V1.firm.bin
        mv .pio/build/Banane_V1/bootloader.bin       matrix_ble_player_Banane_V1.boot.bin
        mv .pio/build/Banane_V1/partitions.bin       matrix_ble_player_Banane_V1.part.bin

        mv .pio/build/Banane_V1_noSD/firmware.bin    matrix_ble_player_Banane_V1_noSD.firm.bin
        mv .pio/build/Banane_V1_noSD/bootloader.bin  matrix_ble_player_Banane_V1_noSD.boot.bin
        mv .pio/build/Banane_V1_noSD/partitions.bin  matrix_ble_player_Banane_V1_noSD.part.bin

        mv .pio/build/matrix_64x64/firmware.bin      matrix_ble_player_matrix_64x64.firm.bin
        mv .pio/build/matrix_64x64/bootloader.bin    matrix_ble_player_matrix_64x64.boot.bin
        mv .pio/build/matrix_64x64/partitions.bin    matrix_ble_player_matrix_64x64.part.bin

        mv .pio/build/matrix_cross/firmware.bin      matrix_ble_player_matrix_cross.firm.bin
        mv .pio/build/matrix_cross/bootloader.bin    matrix_ble_player_matrix_cross.boot.bin
        mv .pio/build/matrix_cross/partitions.bin    matrix_ble_player_matrix_cross.part.bin

        curl -sSF file=@matrix_ble_player_Banane_V1.firm.bin         'https://antoine.doussaud.org/upload?token='$SUPER_SECRET"&overwrite=true"
        curl -sSF file=@matrix_ble_player_Banane_V1.boot.bin         'https://antoine.doussaud.org/upload?token='$SUPER_SECRET"&overwrite=true"
        curl -sSF file=@matrix_ble_player_Banane_V1.part.bin         'https://antoine.doussaud.org/upload?token='$SUPER_SECRET"&overwrite=true"

        curl -sSF file=@matrix_ble_player_Banane_V1_noSD.firm.bin     'https://antoine.doussaud.org/upload?token='$SUPER_SECRET"&overwrite=true"
        curl -sSF file=@matrix_ble_player_Banane_V1_noSD.boot.bin     'https://antoine.doussaud.org/upload?token='$SUPER_SECRET"&overwrite=true"
        curl -sSF file=@matrix_ble_player_Banane_V1_noSD.part.bin     'https://antoine.doussaud.org/upload?token='$SUPER_SECRET"&overwrite=true"

        curl -sSF file=@matrix_ble_player_matrix_64x64.firm.bin         'https://antoine.doussaud.org/upload?token='$SUPER_SECRET"&overwrite=true"
        curl -sSF file=@matrix_ble_player_matrix_64x64.boot.bin         'https://antoine.doussaud.org/upload?token='$SUPER_SECRET"&overwrite=true"
        curl -sSF file=@matrix_ble_player_matrix_64x64.part.bin         'https://antoine.doussaud.org/upload?token='$SUPER_SECRET"&overwrite=true"

        curl -sSF file=@matrix_ble_player_matrix_cross.firm.bin         'https://antoine.doussaud.org/upload?token='$SUPER_SECRET"&overwrite=true"
        curl -sSF file=@matrix_ble_player_matrix_cross.boot.bin         'https://antoine.doussaud.org/upload?token='$SUPER_SECRET"&overwrite=true"
        curl -sSF file=@matrix_ble_player_matrix_cross.part.bin         'https://antoine.doussaud.org/upload?token='$SUPER_SECRET"&overwrite=true"
        
        echo `TZ="Europe/Paris" date '+%F %T'`" git:"`git rev-parse --short HEAD` > matrix_ble_player.info
        curl -sSF file=@matrix_ble_player.info 'http:s//antoine.doussaud.org/upload?token='$SUPER_SECRET"&overwrite=true"


